# Generated by Django 5.1.7 on 2025-03-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='project',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
